### ISSUE TITLE
"Cannot Find module ./db.json"

### ISSUE THREAD

**Issue by Valik1** [Astrydax/SWEotE-Discord-Dice-Roller#1]
![error](https://cloud.githubusercontent.com/assets/26474558/24027569/76120138-0a96-11e7-89cb-5ff9dc2e106c.PNG)
Error persists in both Master and 1.02 versions, through multiple un/installations.

**Comment by Lordjosh286** [comment]
Make sure in the drop down menu that you have the check next to version 1.02

![capture](https://cloud.githubusercontent.com/assets/26561423/24131312/36915bb8-0dc4-11e7-8314-868ff0e109cc.PNG)

**Comment by Astrydax** [comment]
For a temporary fix, make sure you've downloaded from the master branch. 

Open the console.bat file. Type "npm install" this will grab all the bot dependencies. 
If you're on a Mac, just open a terminal and navigate to the bot folder, and type the same command.

**Comment by Astrydax** [comment]
As a temporary fix, Make sure you've downloaded from the master branch. 

Delete the "node_modules" folder.  Open the "console.bat" file. type "npm install" and press enter.

This should properly install all the bot's dependencies.

**Comment by Astrydax** [comment]
This issue should no longer occur. If you like you can delete what you have and download the newest version of the bot from the master branch. The above method in my previous comment will still fix the issue however. There is a new file that says "run this before first launch". This should take care of the issue all together. I've also included this in the updated readme file.
