### ISSUE TITLE
Add force dice emoji

### ISSUE THREAD

**Issue by SkyJedi** [Astrydax/SWEotE-Discord-Dice-Roller#11]
I have them. I'll wait until the emoji merge to put them in.

![screen shot 2017-03-23 at 9 39 32 pm](https://cloud.githubusercontent.com/assets/2967416/24278529/5d98a1a8-1012-11e7-9dde-ef9fda9f254c.png)

**Comment by SkyJedi** [comment]
https://github.com/Astrydax/SWEotE-Discord-Dice-Roller/commit/c633111b3998fda3dbc9396fcd41abbdcc39f771

**Comment by Astrydax** [comment]
#14
