### ISSUE TITLE
Emoji Size

### ISSUE THREAD

**Issue by SkyJedi** [Astrydax/SWEotE-Discord-Dice-Roller#12]
When the bot displays the dice the emoji are small for some reason.  I think it has to so with being on the same line as text.  Maybe eliminate the text or force a line break?

![screenshot_20170323-202649](https://cloud.githubusercontent.com/assets/2967416/24278590/a246ad36-1012-11e7-86f0-e450651c8fb4.png)

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/ac4f9116435f7a785609de590cdb10dd46d089a1 
![screen shot 2017-03-24 at 8 53 35 am](https://cloud.githubusercontent.com/assets/2967416/24297318/59ef1380-1070-11e7-81d6-3f2879e715e7.png)

**Comment by Astrydax** [comment]
Implemented in PR: #16
