### ISSUE TITLE
Emoji Update

### ISSUE THREAD

**Issue by Astrydax** [Astrydax/SWEotE-Discord-Dice-Roller#15]
#14 I've merged this PR into the emoji branch. Lets focus on just the emoji implementation so we can get that merged into the master branch ASAP.  The only reason I can't merge it into master right now, is because some people using the bot don't have Emoji set up on their server.  To account for this, we'll need to add a boolean setting in config.json for "useEmoji": false. If they want to use emoji, they can add the images to their server and then set this value to true.  For main.js, we'll need to add IF statements around the response string builders, that adds the normal text response if config.useEmoji == false, and adds emoji if config.useEmoji == true. @SkyJedi 

We'll need to start working in the emoji branch for a bit to add this. I'm moving into a new flat this week so I'll be MIA for awhile. But i'll get back to this as soon as I'm settled.

**Comment by SkyJedi** [comment]
implemented in PR https://github.com/Astrydax/SWEotE-Discord-Dice-Roller/pull/16
