### ISSUE TITLE
Crit roller

### ISSUE THREAD

**Issue by SkyJedi** [Astrydax/SWEotE-Discord-Dice-Roller#17]
I'm going to take a stab at making a roller for critical hits that will roll a d100 add/sub a modifiers while appropriate and then output the resulting critcal hit information.

!crit

**Comment by Astrydax** [comment]
someone already did that https://github.com/Astrydax/SWEotE-Discord-Dice-Roller/pull/3
but his implementation will cause bugs, Just need to edit his code a bit. Read my comments on that PR listing

**Comment by SkyJedi** [comment]
I fixed his d100 +modifier code here https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/da53ccbbb74bca3466dcab33174e61a0c86f8982

I want to add a text output of what each number roll means.  
![screen shot 2017-03-25 at 8 36 19 am](https://cloud.githubusercontent.com/assets/2967416/24322625/400acb82-1136-11e7-87e4-02e475fe50f3.png)

I'm working on it.  It'll be a new command !crit.  And there is another table for vehicle combat too that i should add once i get !crit working.

**Comment by Astrydax** [comment]
you could create a command that just DMs the user with that picture, or puts it into the channel
no real reason to type if up from scratch when that picture is perfect

**Comment by SkyJedi** [comment]
https://github.com/Astrydax/SWEotE-Discord-Dice-Roller/pull/20
