### ISSUE TITLE
No D100 Roller

### ISSUE THREAD

**Issue by Lordjosh286** [Astrydax/SWEotE-Discord-Dice-Roller#2]
Would appreciate adding in code for a D100 roll for critical injuries

**Comment by Astrydax** [comment]
This is implemented as of now in version 1.0.3

**Comment by Lordjosh286** [comment]
Could I get the code so I can add it in on my end until you release 1.0.3?

**Comment by Lordjosh286** [comment]
Does not display my d100 roll results 

![no result](https://cloud.githubusercontent.com/assets/26561423/24178987/da4f2cee-0e82-11e7-9e92-0822858da211.PNG)

**Comment by Lordjosh286** [comment]
Im getting an undefined end in the command prompt as well. 

![capture](https://cloud.githubusercontent.com/assets/26561423/24180685/c14aa354-0e8c-11e7-95e4-7263f9e92aac.PNG)

**Comment by Astrydax** [comment]
The command is simply !d100, my apologies I should have explained. This roll has to be separate from a "!roll [dice}" command.  This is a quick fix for the time being, working the !d100 roll into the existing modular !roll command will take more time.  

That undefined readout is harmless, that occurs if you don't add a comment to the !roll command. Those readouts were for development, I just forgot to remove them before pushing to github.

**Comment by Lordjosh286** [comment]
Is there a way I could code in a thing for modifiers like +50? I appreciate you getting back to me. However I think I can figure out a way to get it to go off of the !roll like most commands. In the comment for D100 just add "Roll d100". Would that work?

**Comment by Astrydax** [comment]
@Lordjosh286  Yeah, fork the repo,  add your changes then do a pull request. I'll review the code and incorporate the changes. Although I will say that I know how to make that happen as well, I just don't have the time right now to make that happen. Other projects and moving into a new flat that doesn't have internet yet is limiting my time greatly. But if you think you can make it happen sooner than I can, then by all means please fork and PR

**Comment by Lordjosh286** [comment]
Will do! I'm going to see if I can get a modifier to work then I'll create the pull request

**Comment by Astrydax** [comment]
I will warn you though, If you're using a linter, I ignored a lot of the redefining errors because I'm just use to using Var, instead of Let. Be prepared for harmless errors. I learned JS a long time ago and just came back so I'm still learning all this ES6 stuff

**Comment by Lordjosh286** [comment]
All good! I am doing a crash course on Java. I learned C++ and Visual Basic and saw this and was trying to play around with it. Its nice having a set of 2nd eyes on the code to help fix harmless errors and get it to do some things users might want to do like crit rolls with modifiers and making sure they won't have to change commands from !roll to something like !d100 since my players were doing that all night until I went in and did that minor change. Still working on the modifier hopefully I can get something to work and help out :)

**Comment by Astrydax** [comment]
what do you mean specifically when you say modifiers? Do you mean keeping the d100 over 50? or adding 50 to the existing roll?

**Comment by Lordjosh286** [comment]
In this case it would be adding 50 to the existing roll. I think I figured the code out to modify it on my end to make it work. I can get it to add using the !d100 command however I am modifying the code on my end to allow me to use my !roll d100 command and do the math to get a total result like 106

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/da53ccbbb74bca3466dcab33174e61a0c86f8982
![screen shot 2017-03-24 at 9 40 51 am](https://cloud.githubusercontent.com/assets/2967416/24299100/0498c268-1076-11e7-8036-0cd49d5faaf1.png)
