### ISSUE TITLE
Display individual dies results

### ISSUE THREAD

**Issue by SkyJedi** [Astrydax/SWEotE-Discord-Dice-Roller#4]
There are a couple of instances where players will reroll individual dice. If the result displayed both the individual die results along with the final pool result that would be advantageous.

**Comment by SkyJedi** [comment]
Ive managed to figure it out by blindly stabbing with a battleaxe in the dark at the code. I added some custom emoji for pretty. 

![screen shot 2017-03-22 at 5 23 06 pm](https://cloud.githubusercontent.com/assets/2967416/24223704/61a1824e-0f25-11e7-9cf5-24afe06e232e.png)

**Comment by Astrydax** [comment]
can you do a pull request with this code?

**Comment by SkyJedi** [comment]
Let me finish up and I'll send a request.  Right now it just works for the green die

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/97b5171c767cac08a365c5141e930af434f99ad5

**Comment by SkyJedi** [comment]
See in action here 

https://discord.gg/G8au6FH

**Comment by Astrydax** [comment]
Implemented in PR: #16
