### ISSUE TITLE
Error: Cannot find module 'firebase'

### ISSUE THREAD

**Issue by Kovaelin** [Astrydax/SWEotE-Discord-Dice-Roller#53]
I was trying to follow your instructions for setting up, but I'm confused about the part that references Firebase. Would you be able to provide some clarification at this point? Also, you say to save at step 15, but then there's an additional change at step 16. Does the User ID not actually matter, or should we be saving at Step 16 instead? Thank you.

**Comment by Kovaelin** [comment]
Was this resolved in a newer version? No explanation before closing the issue?

**Comment by SkyJedi** [comment]
my repo is the most updated here https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller

also you can invite a prebuilt bot with this link so you dont have to host your own https://discordapp.com/oauth2/authorize?client_id=294576386696544273&scope=bot&permissions=262144

**Comment by Kovaelin** [comment]
Thanks!
