### ISSUE TITLE
Destiny Points

### ISSUE THREAD

**Issue by SkyJedi** [Astrydax/SWEotE-Discord-Dice-Roller#7]
I'm going to work on a Module to check track of destiny points.  Hopefully the commands will work like below. as I'm not a coder help would be appreciated.

!destiny status - shows current destiny points
!destiny light - uses a light side point, displays new balance
!destiny dark - uses dark side point, displays new balance 
!destiny set XL XD - Sets the balance and number of points
!destiny reset - clears the point

**Comment by SkyJedi** [comment]
nm easier than i thought, creating pull request

final commands 
!destiny shows current destiny points
!destiny light - uses a light side point, displays new balance
!destiny dark - uses dark side point, displays new balance
!destiny set Xl Xd - Sets the balance and number of points
!destiny reset - clears the pool

![screen shot 2017-03-23 at 2 03 29 pm](https://cloud.githubusercontent.com/assets/2967416/24265493/bf5b6830-0fd1-11e7-91f5-36d58eaa104d.png)

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/4d7d6388cc665e15707ce6c17b155b8d078f3877

**Comment by Astrydax** [comment]
Implemented in PR: #16
